module Errno

  E2BIG = Errno::E2BIG
  EACCES = Errno::EACCES
  EADDRINUSE = Errno::EADDRINUSE
  EADDRNOTAVAIL = Errno::EADDRNOTAVAIL
  EAFNOSUPPORT = Errno::EAFNOSUPPORT
  EAGAIN = Errno::EAGAIN
  EALREADY = Errno::EALREADY
  EBADF = Errno::EBADF
  EBUSY = Errno::EBUSY
  ECHILD = Errno::ECHILD
  ECONNABORTED = Errno::ECONNABORTED
  ECONNREFUSED = Errno::ECONNREFUSED
  ECONNRESET = Errno::ECONNRESET
  EDEADLK = Errno::EDEADLK
  EDEADLOCK = Errno::EDEADLK
  EDESTADDRREQ = Errno::EDESTADDRREQ
  EDOM = Errno::EDOM
  EDQUOT = Errno::EDQUOT
  EEXIST = Errno::EEXIST
  EFAULT = Errno::EFAULT
  EFBIG = Errno::EFBIG
  EHOSTDOWN = Errno::EHOSTDOWN
  EHOSTUNREACH = Errno::EHOSTUNREACH
  EILSEQ = Errno::EILSEQ
  EINPROGRESS = Errno::EINPROGRESS
  EINTR = Errno::EINTR
  EINVAL = Errno::EINVAL
  EIO = Errno::EIO
  EISCONN = Errno::EISCONN
  EISDIR = Errno::EISDIR
  ELOOP = Errno::ELOOP
  EMFILE = Errno::EMFILE
  EMLINK = Errno::EMLINK
  EMSGSIZE = Errno::EMSGSIZE
  ENAMETOOLONG = Errno::ENAMETOOLONG
  ENETDOWN = Errno::ENETDOWN
  ENETRESET = Errno::ENETRESET
  ENETUNREACH = Errno::ENETUNREACH
  ENFILE = Errno::ENFILE
  ENOBUFS = Errno::ENOBUFS
  ENODEV = Errno::ENODEV
  ENOENT = Errno::ENOENT
  ENOEXEC = Errno::ENOEXEC
  ENOLCK = Errno::ENOLCK
  ENOMEM = Errno::ENOMEM
  ENOPROTOOPT = Errno::ENOPROTOOPT
  ENOSPC = Errno::ENOSPC
  ENOSYS = Errno::ENOSYS
  ENOTCONN = Errno::ENOTCONN
  ENOTDIR = Errno::ENOTDIR
  ENOTEMPTY = Errno::ENOTEMPTY
  ENOTSOCK = Errno::ENOTSOCK
  ENOTTY = Errno::ENOTTY
  ENXIO = Errno::ENXIO
  EOPNOTSUPP = Errno::EOPNOTSUPP
  EPERM = Errno::EPERM
  EPFNOSUPPORT = Errno::EPFNOSUPPORT
  EPIPE = Errno::EPIPE
  EPROTONOSUPPORT = Errno::EPROTONOSUPPORT
  EPROTOTYPE = Errno::EPROTOTYPE
  ERANGE = Errno::ERANGE
  EREMOTE = Errno::EREMOTE
  EROFS = Errno::EROFS
  ESHUTDOWN = Errno::ESHUTDOWN
  ESOCKTNOSUPPORT = Errno::ESOCKTNOSUPPORT
  ESPIPE = Errno::ESPIPE
  ESRCH = Errno::ESRCH
  ESTALE = Errno::ESTALE
  ETIMEDOUT = Errno::ETIMEDOUT
  ETOOMANYREFS = Errno::ETOOMANYREFS
  EUSERS = Errno::EUSERS
  EWOULDBLOCK = Errno::EWOULDBLOCK
  EXDEV = Errno::EXDEV



  protected


  private

end
