$-d = false
$LOAD_PATH = ["C:/Ruby187/lib/ruby/site_ruby/1.8", "C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt", "C:/Ruby187/lib/ruby/site_ruby", "C:/Ruby187/lib/ruby/vendor_ruby/1.8", "C:/Ruby187/lib/ruby/vendor_ruby/1.8/i386-msvcrt", "C:/Ruby187/lib/ruby/vendor_ruby", "C:/Ruby187/lib/ruby/1.8", "C:/Ruby187/lib/ruby/1.8/i386-mingw32", "."]
$stdin = IO.new
$~ = nil
$-F = nil
$-a = false
$VERBOSE = false
$_ = nil
$-K = "NONE"
$0 = "C:/Users/Ian Brown-Kirk.Layle7/AppData/Roaming/Appcelerator/Aptana Studio/configuration/org.eclipse.osgi/bundles/90/1/.cp/ruby/core_stubber.rb"
$> = IO.new
$/ = "\n"
$' = nil
$@ = nil
$fileutils_rb_have_lchmod = nil
$DEBUG = false
$-I = ["C:/Ruby187/lib/ruby/site_ruby/1.8", "C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt", "C:/Ruby187/lib/ruby/site_ruby", "C:/Ruby187/lib/ruby/vendor_ruby/1.8", "C:/Ruby187/lib/ruby/vendor_ruby/1.8/i386-msvcrt", "C:/Ruby187/lib/ruby/vendor_ruby", "C:/Ruby187/lib/ruby/1.8", "C:/Ruby187/lib/ruby/1.8/i386-mingw32", "."]
$; = nil
$. = 1598
$KCODE = "NONE"
$-l = false
$LOADED_FEATURES = ["enumerator.so", "etc.so", "fileutils.rb"]
$stderr = IO.new
$, = nil
$` = nil
$-w = false
$: = ["C:/Ruby187/lib/ruby/site_ruby/1.8", "C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt", "C:/Ruby187/lib/ruby/site_ruby", "C:/Ruby187/lib/ruby/vendor_ruby/1.8", "C:/Ruby187/lib/ruby/vendor_ruby/1.8/i386-msvcrt", "C:/Ruby187/lib/ruby/vendor_ruby", "C:/Ruby187/lib/ruby/1.8", "C:/Ruby187/lib/ruby/1.8/i386-mingw32", "."]
$? = nil
$< = ARGF
$* = ["C:\\Users\\Ian Brown-Kirk.Layle7\\Documents\\GitHub\\IPL-Ruby\\.metadata\\.plugins\\com.aptana.ruby.core\\195679908\\4"]
$-i = nil
$deferr = IO.new
$\ = nil
$= = false
$fileutils_rb_have_lchown = nil
$-p = false
$" = ["enumerator.so", "etc.so", "fileutils.rb"]
$stdout = IO.new
$& = nil
$-v = false
$$ = 16804
$PROGRAM_NAME = "C:/Users/Ian Brown-Kirk.Layle7/AppData/Roaming/Appcelerator/Aptana Studio/configuration/org.eclipse.osgi/bundles/90/1/.cp/ruby/core_stubber.rb"
$FILENAME = "-"
$defout = IO.new
$-0 = "\n"
$+ = nil
$SAFE = 0
$! = nil
